### ISSUE TITLE
very large code blocks

### ISSUE THREAD

**Issue by 9il** [DlangScience/bootDoc#2]
<img width="208" alt="screen shot 2016-04-16 at 21 24 40" src="https://cloud.githubusercontent.com/assets/845083/14583164/d537efa8-0419-11e6-9ffe-a869c0290cb5.png">

**Comment by wilzbach** [comment]
should be fixed by #1 - did you update?

**Comment by 9il** [comment]
no

**Comment by 9il** [comment]
still large

**Comment by wilzbach** [comment]
I think I found the issue - see https://github.com/DlangScience/mir/pull/145

**Comment by wilzbach** [comment]
... and it worked :)
